/**
 * Database Types
 *
 * This file is auto-generated by Supabase CLI.
 * Run `npm run db:types` to regenerate after schema changes.
 *
 * Manual types are provided below until connected to a Supabase project.
 */

export interface Database {
    public: {
        Tables: {
            leads: {
                Row: {
                    id: string;
                    first_name: string;
                    last_name: string;
                    email: string;
                    company: string;
                    nmls_id: string | null;
                    message: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    first_name: string;
                    last_name: string;
                    email: string;
                    company: string;
                    nmls_id?: string | null;
                    message?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    first_name?: string;
                    last_name?: string;
                    email?: string;
                    company?: string;
                    nmls_id?: string | null;
                    message?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Relationships: [];
            };
        };
        Views: Record<string, never>;
        Functions: Record<string, never>;
        Enums: Record<string, never>;
    };
}

// Convenience types
export type Lead = Database['public']['Tables']['leads']['Row'];
export type LeadInsert = Database['public']['Tables']['leads']['Insert'];
export type LeadUpdate = Database['public']['Tables']['leads']['Update'];
